// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmV6J-6WqjsFA8OvorkbZYYz7iUuCRcn0',
    appId: '1:1005920005280:web:0bc8db062b1933105f6dc5',
    messagingSenderId: '1005920005280',
    projectId: 'chat-app-32988',
    authDomain: 'chat-app-32988.firebaseapp.com',
    storageBucket: 'chat-app-32988.appspot.com',
    measurementId: 'G-F22E7K7P9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrbRgpFGtn-uUXl0Tqg9_rjlug9tvc880',
    appId: '1:1005920005280:android:0acf6999373319835f6dc5',
    messagingSenderId: '1005920005280',
    projectId: 'chat-app-32988',
    storageBucket: 'chat-app-32988.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOBHxrbmpIkuJ--lMyLHGOcBThlFApJPE',
    appId: '1:1005920005280:ios:318404f53827af425f6dc5',
    messagingSenderId: '1005920005280',
    projectId: 'chat-app-32988',
    storageBucket: 'chat-app-32988.appspot.com',
    iosClientId: '1005920005280-p2p4l3898nemlmitbrt5cjpqsegh18pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOBHxrbmpIkuJ--lMyLHGOcBThlFApJPE',
    appId: '1:1005920005280:ios:318404f53827af425f6dc5',
    messagingSenderId: '1005920005280',
    projectId: 'chat-app-32988',
    storageBucket: 'chat-app-32988.appspot.com',
    iosClientId: '1005920005280-p2p4l3898nemlmitbrt5cjpqsegh18pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
